# Rebuild the checked-in notice bundle from the dependencies used by this build.
# Upstream notice snapshots are grouped by component in third_party; this script
# never downloads models or license texts. Run again when dependencies change.
param([string]$VcpkgInstalledDir = '')
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$setup = Join-Path $root 'installer/FaceLoginSetup'
$utf8 = New-Object System.Text.UTF8Encoding($false)

function Read-Text([string]$Path) {
    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) { throw "Missing license source: $Path" }
    return [System.IO.File]::ReadAllText($Path).Replace("`r`n", "`n").TrimEnd()
}
function Sort-Ordinal([string[]]$Values) {
    # PowerShell 5 and 7 use different culture collations for hyphenated names.
    [Array]::Sort($Values, [StringComparer]::Ordinal)
    return $Values
}
$bundle = New-Object System.Text.StringBuilder
function Add-Section([string]$Title, [string]$Origin, [string]$Path) {
    [void]$bundle.Append("`n================================================================`n$Title`n$Origin`n================================================================`n`n")
    [void]$bundle.Append((Read-Text $Path) + "`n")
}
function Legal-Files([string]$Dir) {
    $paths = @(Get-ChildItem -LiteralPath $Dir -File | Where-Object {
        $_.Name -match '^(LICENSE|LICENCE|COPYING|NOTICE|NOTICES|PATENTS)([._-].*)?$'
    } | Select-Object -ExpandProperty FullName)
    foreach ($path in (Sort-Ordinal $paths)) { Get-Item -LiteralPath $path }
}

[void]$bundle.Append(@'
FaceLogin - Third-party notices

Generated by scripts/update_third_party_notices.ps1. Original license texts are
preserved below; headings identify the component and the source of each text.
FaceLogin's own code license is in LICENSE.txt (LICENSE in the source tree).
Pretrained model terms and unresolved permissions are in MODEL_LICENSES.md
(docs/model-licenses.md in the source tree). This bundle does not grant any
additional rights to pretrained weights.

The C++ section covers the installed ONNX Runtime dependency closure, including
headers and supporting build packages. ONNX Runtime's complete upstream notices
also mention optional components; inclusion here does not mean every optional
component is enabled in FaceLogin. Go entries cover the Windows production
dependency graph. Frontend entries cover Vue, Tailwind styles and Vite's emitted
browser helpers. These component licenses apply to their respective material.

'@)

# Respect CMake's actual installed tree, which may differ from root/vcpkg_installed.
if (-not $VcpkgInstalledDir) {
    $cache = Join-Path $root 'build/CMakeCache.txt'
    if (Test-Path -LiteralPath $cache) {
        $match = Select-String -LiteralPath $cache -Pattern '^VCPKG_INSTALLED_DIR:PATH=(.+)$'
        if ($match) { $VcpkgInstalledDir = $match.Matches[0].Groups[1].Value }
    }
    if (-not $VcpkgInstalledDir) { $VcpkgInstalledDir = Join-Path $root 'vcpkg_installed' }
}
$status = Read-Text (Join-Path $VcpkgInstalledDir 'vcpkg/status')
$packages = @{}
foreach ($record in ($status -split "`n`n")) {
    if ($record -notmatch '(?m)^Package: (.+)$') { continue }
    $name = $Matches[1].Trim()
    if ($record -notmatch '(?m)^Version: (.+)$') { continue }
    $version = $Matches[1].Trim()
    $deps = @()
    if ($record -match '(?m)^Depends: (.+)$') { $deps = $Matches[1] -split ', ' }
    if (-not $packages.ContainsKey($name)) { $packages[$name] = @{ version = $version; deps = $deps } }
}
if (-not $packages.ContainsKey('onnxruntime')) { throw 'ONNX Runtime is not installed in the selected vcpkg tree.' }
$closure = @{}
function Visit-Package([string]$Name) {
    # These ports install build infrastructure, not redistributed C++ material.
    if ($Name -like 'vcpkg-*' -or $Name -in @('boost-cmake', 'boost-uninstall') -or $closure.ContainsKey($Name)) { return }
    if (-not $packages.ContainsKey($Name)) { throw "Missing installed dependency: $Name" }
    $closure[$Name] = $packages[$Name]
    foreach ($dependency in $packages[$Name].deps) {
        if ($dependency -match '^([a-z0-9-]+)') { Visit-Package $Matches[1] }
    }
}
Visit-Package 'onnxruntime'
foreach ($name in (Sort-Ordinal @($closure.Keys))) {
    $version = $closure[$name].version
    $origin = "Source: installed vcpkg package $name $version, share/$name/copyright"
    if ($name -eq 'eigen3') {
        $origin += "`nCorresponding Eigen source (MPL-2.0): https://gitlab.com/libeigen/eigen/-/tree/$version"
        $origin += "`nFaceLogin makes no source changes to Eigen; the vcpkg port installs its headers."
    }
    Add-Section "C++ dependency: $name $version" $origin (Join-Path $VcpkgInstalledDir "x64-windows/share/$name/copyright")
}

$thirdParty = Join-Path $root 'third_party'
$snapshots = Get-Content -LiteralPath (Join-Path $thirdParty 'sources.json') -Raw | ConvertFrom-Json
$ortVersion = $packages['onnxruntime'].version
if (-not ($snapshots | Where-Object { $_.component -eq 'onnxruntime' -and $_.version -eq $ortVersion })) {
    throw "Add a verified ONNX Runtime $ortVersion notice snapshot to third_party/sources.json."
}
foreach ($source in $snapshots) {
    if ($source.distributed -eq $false) { continue }
    if ($source.component -eq 'onnxruntime' -and $source.version -ne $ortVersion) { continue }
    $path = Join-Path $thirdParty $source.file
    if ((Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash -ine $source.sha256) {
        throw "Upstream license snapshot hash mismatch: $($source.file)"
    }
    Add-Section "$($source.component) - upstream notice snapshot" "Source: $($source.url)" $path
}

$wvDir = Join-Path $root 'enrollment_app/webview2'
[xml]$nuspec = Read-Text (Join-Path $wvDir 'Microsoft.Web.WebView2.nuspec')
$wvVersion = $nuspec.package.metadata.version
foreach ($file in @('LICENSE.txt', 'NOTICE.txt')) {
    Add-Section "Microsoft WebView2 SDK $wvVersion - $file" "Source: Microsoft.Web.WebView2 NuGet package; includes the console's static loader." (Join-Path $wvDir $file)
}

# -e permits only the two generated embed inputs to be absent on a fresh clone.
# Dependency resolution failures still stop generation instead of omitting notices.
Push-Location $setup
try {
    $rows = & go list -e -deps -tags desktop,wv2runtime.download,production -f '{{if .Error}}{{.ImportPath}}|ERROR|{{.Error.Err}}{{else if .Module}}{{.Module.Path}}|{{.Module.Version}}|{{.Module.Dir}}|{{.Dir}}{{end}}' .
    if ($LASTEXITCODE -ne 0) { throw 'go list failed.' }
    $goroot = (& go env GOROOT).Trim()
    $goversion = (& go env GOVERSION).Trim()
} finally { Pop-Location }
$seen = @{}
foreach ($row in (Sort-Ordinal @($rows | Where-Object { $_ } | Select-Object -Unique))) {
    $fields = $row -split '\|', 4
    if ($fields[1] -eq 'ERROR') {
        if ($fields[0] -eq 'FaceLoginSetup' -and $fields[2] -match 'pattern (all:frontend/dist|payload.zip): no matching files found') { continue }
        throw "Dependency resolution failed: $row"
    }
    if ($fields[0] -eq 'FaceLoginSetup') { continue }
    $moduleDir = $fields[2]
    $packageDir = $fields[3]
    $legal = @(Legal-Files $moduleDir)
    if ($legal.Count -eq 0) { throw "No root license found for Go module $($fields[0])" }
    # Nested packages can have separate terms, e.g. go-webview2/webviewloader.
    while ($packageDir -and $packageDir.Length -gt $moduleDir.Length) {
        $legal += @(Legal-Files $packageDir)
        $packageDir = Split-Path -Parent $packageDir
    }
    foreach ($path in (Sort-Ordinal @($legal.FullName | Select-Object -Unique))) {
        $file = Get-Item -LiteralPath $path
        if ($seen.ContainsKey($file.FullName)) { continue }
        $seen[$file.FullName] = $true
        $relative = $file.FullName.Substring($moduleDir.Length + 1).Replace('\', '/')
        Add-Section "Go: $($fields[0]) $($fields[1]) - $relative" 'Source: the versioned Go module cache, corresponding to go.mod/go.sum.' $file.FullName
    }
}
foreach ($file in (Legal-Files $goroot)) {
    Add-Section "Go standard library/runtime $goversion - $($file.Name)" 'Source: the Go toolchain used to compile the installer.' $file.FullName
}

foreach ($name in @('vue', '@vue/shared', '@vue/reactivity', '@vue/runtime-core', '@vue/runtime-dom', 'tailwindcss', 'vite')) {
    $dir = Join-Path $setup "frontend/node_modules/$name"
    $package = Get-Content -LiteralPath (Join-Path $dir 'package.json') -Raw | ConvertFrom-Json
    $files = @(Legal-Files $dir)
    if ($files.Count -eq 0) { throw "No license found for frontend package $name" }
    foreach ($file in $files) {
        Add-Section "Frontend: $name $($package.version) - $($file.Name)" 'Source: the installed npm package, corresponding to frontend/package-lock.json.' $file.FullName
    }
}

$out = Join-Path $root 'THIRD_PARTY_NOTICES.txt'
[System.IO.File]::WriteAllText($out, $bundle.ToString(), $utf8)
& (Join-Path $PSScriptRoot 'stage_licenses.ps1')
Write-Host "Updated THIRD_PARTY_NOTICES.txt and staged distribution copies."
